replace .flag("-O").opt_level(0) with .opt_level(1) because they have the same effect
I set -O - literally all I did. I passed added a compiler flag -O and
nothing else. and it makes things work. I don't get a
```
ERROR panicked at 'called `Result::unwrap()` on an `Err` value:
```
this should do literally nothing because -O requires an ARGUMENT.
I shouldn't have found this solution because it should have done nothing

it works with just .opt_level(1) except on release, so we're getting closer.