Add -O flag to cc and remove load bearing defmt
Errors resulting from the era before this change still puzzle me - there is some undefined behavior here, somewhere. because these shouldn't have happened:

>testsuite/test/test.rs
```
let optiga_result = device.sha256(&samplebits).unwrap();

assert_eq!(optiga_result, known_good_hash_result[..]);
```

```
ERROR panicked at 'called `Result::unwrap()` on an `Err` value:
```

>testsuite/test/test.rs
```
let optiga_result = device.sha256(&samplebits);

assert_eq!(optiga_result.unwrap(), known_good_hash_result[..]);
```

```
ERROR panicked at 'assertion failed: `(left == right)`'
diff < left / right >
<[255, 1, 32, 31, 164, 1, 8, 3, 0, 0, 0, 1, 0, 0, 0, 99, 255, 1, 32, 44, 4, 0, 32, 99, 255, 1, 32, 1, 0, 0, 0, 76]
>[186, 120, 22, 191, 143, 1, 207, 234, 65, 65, 64, 222, 93, 174, 34, 35, 176, 3, 97, 163, 150, 23, 122, 156, 180, 16, 255, 97, 242, 0, 21, 173]
```

>adding defmt trace before the Ok(hash_buffer) in sha256

```
all tests passed!
```

when the unwrap moved, it failed in different ways. a defmt trace was magically load bearing.
When I eventually responded to this error:

```
warning _FORTIFY_SOURCE requires compiling with optimization (-O)
```

by adding a compiler flag, in debug mode things started working. they still segfault/die on release, which will be it's own problem, but I am hopeful.